#Intel Databases go here
#MISP
  misp:
    image: harvarditsecurity/misp
    restart: unless-stopped
    ports:
      - "8081:80"
      - "4431:443"
      - "3306:3306"      
    volumes:
      - /dev/urandom:/dev/urandom
      - ./gpg/:/var/www/MISP/.gnupg
      - ./data/db:/var/lib/mysql
    environment:
#      - MISP_BASEURL=http://localhost/
#YETI
  yeti:
    build:
      context: ./yeti
      dockerfile: Dockerfile 
    image: yeti-platform
    ports:
      - 8082:5000
#links:
#  - yeti_redis
#  - mongodb
    restart: unless-stopped
  yeti_redis:
    image: redis:latest
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_LOG_DIR=/dev/null
    command: mongod
#TAXII
  taxii_db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=opentaxii
  authdb:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=password1
      - POSTGRES_DB=opentaxii1
  opentaxii:
    image: eclecticiq/opentaxii
    environment:
      - OPENTAXII_AUTH_SECRET=secret
      - OPENTAXII_DOMAIN=localhost:8083
      - OPENTAXII_USER=user
      - OPENTAXII_PASS=pass
      - DATABASE_HOST=taxi_db
      - DATABASE_NAME=opentaxii
      - DATABASE_USER=user
      - DATABASE_PASS=password
      - AUTH_DATABASE_HOST=authdb
      - AUTH_DATABASE_NAME=opentaxii1
      - AUTH_DATABASE_USER=user1
      - AUTH_DATABASE_PASS=password1
    volumes:
      - ./:/input:ro
    ports:
      - 8083:9000
    links:
    #  - db:db
      - authdb:authdb

  
